modLoader="javafml"
loaderVersion="[14,)"
issueTrackerURL="https://github.com/MrTroble/Wireless-Redstone/issues"
license="Apache License Version 2.0"

[[mods]]
modId="gircredstone"
version="${file.jarVersion}"
displayName="TC Redstone"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo"
description="Wireless Redstone Mod - Works in unloaded Chunks TM."

[[dependencies.gircredstone]]
    modId="forge" 
    mandatory=true 
    versionRange="[14,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.gircredstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.12.2]"
    ordering="NONE"
    side="BOTH"
