modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/German-Immersive-Railroading-Community/GIRC-Redstone/issues"
license="Apache License Version 2.0"

[[mods]]
modId="gircredstone"
version="${file.jarVersion}"
displayName="TC Redstone"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo"
description="Works in unloaded Chunks TM."

[[dependencies.gircredstone]]
    modId="forge" 
    mandatory=true 
    versionRange="[44.0.0,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.gircredstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3, 1.20)"
    ordering="NONE"
    side="BOTH"
